### ISSUE TITLE
register page error

### ISSUE THREAD

**Issue by shopfly-ecommerce** [shopflix/vue-storefront#1]
go to register

<img width="625" alt="image" src="https://user-images.githubusercontent.com/101858373/162394157-919420f9-d8b7-41fd-91c3-106221e7e6ac.png">

**Comment by AndsteLyc** [comment]
Fix at  [ca6a91c](https://github.com/shopflix/vue-storefront/commit/ca6a91c347ebd7243e19bd2917bd795b47bb53d3).
